language: go

os:
  - linux
#  - osx
#  - windows

arch:
  - amd64
#  - arm64
#  - ppc64le
  - s390x

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

jobs:
  allow_failures:
    - go: 'master'
  fast_finish: true

script:
  - go test -v ./...
  - go test -race ./...
  - go test -v ./...
  - go test -v ./...
  - go test -v ./...
  - go test -v ./...
