on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on s390x
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: s390x
          distribution: ubuntu20.04
          run: |
            apt update -y
            apt install curl tar -y
            curl -s -q https://dl.min.io/server/minio/release/linux-s390x/minio -o /usr/bin/minio
            chmod +x /usr/bin/minio
            /usr/bin/minio -version
